site_site:
    resource: "@SiteSiteBundle/Resources/config/routing.yml"
    prefix:   /

site_forum:
    resource: "@SiteForumBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
