<?php

namespace Site\ForumBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubForumRepository extends EntityRepository
{
}
